[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'bash']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
    'chmod +x start.sh'
]

[start]
cmd = 'bash start.sh'
